<?php
$data['user']='axander';
$data['pwd']='gioconda';
$data['active']=true;
$data['privAccess']=true;
$data['privContent']=true;
$data['type']='1';
$data['nick']='axander';
$data['name']='Alejandro';
$data['surname']='surname';
$data['email']='alejandro.martinez@ciberexperis.es';
$data['activator']='1510569893872';
?>