<?php
$data['user']='qfdsfdsf';
$data['pwd']='1234567';
$data['active']=true;
$data['privAccess']=true;
$data['privContent']=true;
$data['type']='1';
$data['nick']='qfdsfdsf';
$data['name']='dfsfsd';
$data['surname']='surname';
$data['email']='fsdfqf@fd.cl';
$data['activator']='1473991924771';
?>